development:
  adapter: mysql
  database: formtastic_development
  username: root
  password:

test:
  adapter: mysql
  database: formtastic_test
  username: root
  password:

production:
  adapter: mysql
  database: formtastic_production
  username: root
  password: 
